require:
  - rubocop-capybara

plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false

Minitest/AssertWithExpectedArgument:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/TestMethodName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Naming/VariableNumber:
  Enabled: false

# False positives per https://github.com/rubocop/rubocop-rails/issues/1269
Rails/ActionControllerFlashBeforeRender:
  Enabled: false

# False positives per https://docs.rubocop.org/rubocop-rails/cops_rails.html#railscompactblank
Rails/CompactBlank:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

# https://github.com/rubocop-hq/rubocop-rails/issues/147
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# Breaks cases with ActiveRecord::Associations::CollectionProxy instead of Array
Style/ArrayIntersect:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashEachMethods:
  Enabled: false
