---
:concurrency: 2
:queues:
  - mailers
  - default
  - active_storage_analysis
  - active_storage_purge
  - ts_delta
  - searchkick
  - user_low
  - low
  - background

:scheduler:
  :schedule:
    script_sync_queueing_job:
      interval: '1m'
      class: ScriptSyncQueueingJob
    subresource_check_queueing_job:
      interval: '1m'
      class: SubresourceCheckQueueingJob
    script_duplicate_checker_queueing_job:
      interval: '1m'
      class: ScriptDuplicateCheckerQueueingJob
    banned_user_delete_job:
      interval: '1h'
      class: BannedUserDeleteJob