---
:concurrency: 2
:queues:
  - mailers
  - default
  - active_storage_analysis
  - active_storage_purge
  - ts_delta
  - searchkick
  - user_low
  - low
  - background

:scheduler:
  :schedule:
    script_sync_queueing_job:
      interval: '1m'
      class: ScriptSyncQueueingJob
