---
:concurrency: 2
:queues:
  - mailers
  - default
  - active_storage_analysis
  - active_storage_purge
  - searchkick
  - user_low
  - low
  - background

:scheduler:
  :schedule:
    script_sync_queueing_job:
      interval: '1m'
      class: ScriptSyncQueueingJob
    subresource_check_queueing_job:
      interval: '1m'
      class: SubresourceCheckQueueingJob
    script_duplicate_checker_queueing_job:
      interval: '1m'
      class: ScriptDuplicateCheckerQueueingJob
    banned_user_delete_job:
      cron: '0 0 0 * * *'
      class: BannedUserDeleteJob
    discussion_read_cleanup_job:
      interval: '1h'
      class: DiscussionReadCleanupJob
    script_page_view_update_job:
      cron: '0 0 3 * * *'
      class: ScriptPageViewUpdateJob
    consecutive_bad_ratings_job:
      interval: '1h'
      class: ConsecutiveBadRatingsJob
    script_delete_job:
      interval: '1h'
      class: ScriptDeleteJob
    delete_old_notifications_job:
      interval: '1h'
      class: DeleteOldNotificationsJob
    akismet_submission_delete_job:
      interval: '1h'
      class: AkismetSubmissionDeleteJob
    stat_ban_checking_job:
      cron: '0 0 1 * * *'
      class: StatBanCheckingJob
    cleaned_code_cleanup_job:
      cron: '0 0 2 * * *'
      class: CleanedCodeCleanupJob
